### PR TITLE
added new setting for pure white colors

### PR DESCRIPTION
**Pull request by OliverHi**
[MySensors] added new setting `usePureWhiteLightInRGBW` to the gateway that makes the RGBW type converter convert a pure white color to a hex value without RGB part (eg. 255 255 255 255 is converted to "000000ff"). This should solve #91

To keep things separated I created a new `MySensorsRGBWPureTypeConverter` class that handles the different conversion but relies on the standard converter for everything but this special case

### CODE REVIEW

**Comment by andreacioni** [comment]
Hi @OliverHi, why did you add `usePureWhiteLightInRGBW` inside `MySensorsBridgeConfiguration` class? Probably the best thing to do is to place it inside `MySensorsSensorConfiguration`. This because you may have on RGBW "standard" and another one RGBW "pure white"

**Comment by OliverHi** [comment]
Hi, I was thinking about that too. I am not sure which place would be more appropriate for the setting. I thought the user might want the same behavior everywhere (thats why I decided to use the bridge).
I can change it though. In the sensorconfig it would be more flexible but also more work to set up (having to add this to every node in the things file)

**Comment by andreacioni** [comment]
Yes you are right, adding same parameter to all the things is redundant. But on the other hand, as I told you previously, if someone have both RGBW "standard" and RGBW "pure white", in your solution, only one of them will work. For me the last one is the worst case and should be avoided 😉

**Comment by OliverHi** [comment]
Ok I moved it to the sensor configuration. There is no need (or way) to constrict this setting just to RGBW nodes, right?

**Comment by andreacioni** [comment]
From what I know, unfortunately, not.

**Comment by tobof** [comment]
Hi @OliverHi !

Thank you for your contribution!

At the moment the new option you've included is not showing up in Paper UI. For the option to show up additions in the corresponding thing file under ESH-INF/thing must be added and in the BindingConstants file.

**Comment by OliverHi** [comment]
@tobof I have just added it to the ESH-INF/thing file but what do I need to add to the other one?
I assume you mean the org.openhab.binding.mysensors.MySensorsBindingConstants.java file, but that does not contain configurations?! It is still a normal RGBW node.

**Comment by OliverHi** [comment]
So I have had a look at it again and can't find another place to add the new parameter. Do they show up now? If I try to build the binding locally I get lots of errors like:
`[ERROR] org.openhab.binding.mysensors.internal.sensors.variable.MySensorsVariableVVar5.java:[2]
Header line doesn't match pattern ^ \* Copyright \(c\) 2010-2018 by the respective copyright holders\.$`
so I can't really test this for myself.
Anything else I can do?

I also pulled your new updates to the branch so that it is mergeable again.

**Pull request merged**
