### PR TITLE
Add CO2 sensor

### PR DESCRIPTION
**Pull request by FutureCow**
I don't know if i did this the right way. Just copy and paste a couple of things around. So it might be completely wrong!

### CODE REVIEW

**Comment by tobof** [comment]
Thank you for the PR!! :+1:

**Comment by andreacioni** [comment]
Hi @FutureCow, just a question about your PR. Why have you created a new channel named "co2-level"? We have already a "level" channel. 
I ask you that because I've done a big refactoring that will be merged soon with Tim work and this change is confusing me 😄. It will be better having only one channel for every MySensors variable because add new one every time we add a sensor could destroy re-usability. What do you think @tobof ?

**Comment by tobof** [comment]
Hey @andreacioni ,

this was exactly my first thought too. Why use a new channel? 
I found an answer and because of that deleted my comment above. ;-)

image

In PaperUI Control the **label** makes a difference. In the item and sitemap configuration you may do what you want.

**Comment by andreacioni** [comment]
@tobof Hmmm ok, but do you think is enough to create a special channel for it? For example if someone want to measure methane we have to add a "methane-level-channel" and so on...

In my opinion the best thing to do is to remove "co2-level-channel" and in paper-ui leave:  "Level" as label. On basic/classic/... ui everyone as the ability to customize label according to his preference.

I say that because if you see changes on [DiscoveryService](https://github.com/tobof/openhab2-addons/pull/44/files#diff-cf2edd1b6bcfbaac5c1435d1818e4f00R194) every new air quality sensor will be added as CO2 sensor (using the "co2-level-channel") and this is wrong.

**Comment by FutureCow** [comment]
@andreacioni 
I think you are right. It was a simple solution for a problem that doesn't exist. So better to leave the label: "Level" and changed it inside the sitemap etc.
I think @tobof already changed CO2-LEVEL thing to AIR_QUALITY?
https://github.com/tobof/openhab2-addons/commit/3d22695dc85ad5513be5a98da8811df9a7f2de4f

**Pull request merged**
